#pragma once

#define FALSE 0
#define TRUE 1

#define GRID_WIDTH 10
#define GRID_HEIGHT 20
#define SQUARE_LENGTH 40

#define WINDOW_TITLE Ime_Prozora
#define WINDOW_WIDTH (GRID_WIDTH * SQUARE_LENGTH)
#define WINDOW_HEIGHT (GRID_HEIGHT * SQUARE_LENGTH)


#define FPS 30
#define FRAME_TARGET_TIME (1000/FPS)
